name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "0.5.8"

      - name: Install dependencies
        run: |
          bun install

      - name: Tests
        run: bun test

  deploy:
    name: "Deploy"
    needs: [tests]
    runs-on: ubuntu-latest
    if: ${{ (github.ref == 'refs/heads/main') && github.event_name == 'push'}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 🚀 Deploy Production
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --remote-only"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
