name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: type-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "0.5.8"

      - name: Install dependencies
        run: |
          bun install

      - name: Tests
        run: bun run test
